version: "3.9"
services:
    jupyter:
        build:
            context: .
            dockerfile: Dockerfile_gpu
        volumes:
            - ${PWD}/code:/code
            - ${PWD}/code/kaggle/input:/kaggle/input
            - ${PWD}/input:/dataset
            - ${PWD}/settings/.kaggle:${HOME_DIR}/.kaggle
            - ${PWD}/settings/.signate:${HOME_DIR}/.signate
            - ${PWD}/settings/jupyterlab-settings/themes.jupyterlab-settings:${HOME_DIR}/.jupyter/lab/user-settings/@jupyterlab/apputils-extension/themes.jupyterlab-settings
            - ${PWD}/settings/jupyterlab-settings/jupyterlab_code_formatter:${HOME_DIR}/.jupyter/lab/user-settings/jupyterlab_code_formatter
        working_dir: /code
        ports:
            - 10000:10000
        command: jupyter lab --ip 0.0.0.0 --allow-root -b localhost --port=10000 --NotebookApp.token=''
        restart: always
        deploy:
            resources:
                reservations:
                    devices:
                        - driver: nvidia
                          capabilities: [gpu]
        env_file:
            - settings/open-api.key

